let name="cty";let age=20;let isStudent=true;let hobbies=["reading","gaming","hiking"];let address={city:"New York",zip:10001};let greet=function(){console.log("Hello, World!");};let person={name:name,age:age,isStudent:isStudent,hobbies:hobbies,address:address,greet:greet};console.log(person);
console.log("Name:", person.name);
console.log("Age:", person.age);
console.log("Is Student:", person.isStudent);
console.log("Hobbies:", person.hobbies.join(", "));
console.log("Address:", person.address.city, person.address.zip);
person.greet();
console.log("Type of name:", typeof name);
console.log("Type of age:", typeof age);
console.log("Type of isStudent:", typeof isStudent);
console.log("Type of hobbies:", typeof hobbies);
console.log("Type of address:", typeof address);
console.log("Type of greet:", typeof greet);    
console.log("Type of person:", typeof person);
console.log("Is person an object?", person instanceof Object);
console.log("Is person an array?", Array.isArray(person));
console.log("Is hobbies an array?", Array.isArray(person.hobbies));
console.log("Is address an object?", person.address instanceof Object);
console.log("Is greet a function?", typeof person.greet === "function");
console.log("Keys of person object:", Object.keys(person));
console.log("Values of person object:", Object.values(person));
console.log("Entries of person object:", Object.entries(person));
console.log("JSON representation of person:", JSON.stringify(person, null, 2));
console.log("Accessing properties using bracket notation:");
console.log("Name:", person["name"]);
console.log("Age:", person["age"]);
console.log("Is Student:", person["isStudent"]);;